"""Updated plant class

Revision ID: 3f8907629257
Revises: ef908493ad79
Create Date: 2023-02-08 14:24:02.289968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f8907629257'
down_revision = 'ef908493ad79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_watered', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=64), nullable=True))
        batch_op.alter_column('purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('avatar')
        batch_op.drop_column('last_watered')

    # ### end Alembic commands ###
