"""empty message

Revision ID: 5369287c768b
Revises: 3f8907629257
Create Date: 2023-02-08 19:43:20.643717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5369287c768b'
down_revision = '3f8907629257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_img', sa.String(length=100000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('plant_img')

    # ### end Alembic commands ###
