"""Set up db

Revision ID: 92f370083ddc
Revises: 
Create Date: 2023-02-03 11:09:15.055398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f370083ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('water_freq', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('plant_data_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('names', sa.String(length=100), nullable=True),
    sa.Column('latin_name', sa.String(length=100), nullable=True),
    sa.Column('min_temp', sa.Integer(), nullable=True),
    sa.Column('max_temp', sa.Integer(), nullable=True),
    sa.Column('ideal_light', sa.String(length=100), nullable=True),
    sa.Column('tolerated_light', sa.String(length=100), nullable=True),
    sa.Column('pests', sa.String(length=100), nullable=True),
    sa.Column('watering', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('climate', sa.String(length=100), nullable=True),
    sa.Column('soil', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('plant__data')
    op.drop_table('plant')
    # ### end Alembic commands ###
