"""empty message

Revision ID: 9e5537c22e12
Revises: 5369287c768b
Create Date: 2023-02-08 19:57:17.268392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5537c22e12'
down_revision = '5369287c768b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('plant_img',
               existing_type=sa.VARCHAR(length=100000),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('plant_img',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=100000),
               existing_nullable=True)

    # ### end Alembic commands ###
